# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-05 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nick', models.CharField(max_length=200, null=True)),
                ('short_desc', models.TextField(blank=True, max_length=300, null=True)),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('image', models.ImageField(null=True, upload_to='articles')),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('permalink', models.CharField(max_length=200, null=True)),
                ('short_desc', models.TextField(blank=True, max_length=300, null=True)),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='flowers')),
                ('tp_master_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField()),
                ('review', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
